application/deployment.yaml 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: model-service-container
        image: unni123123/model-service-image-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
